user www-data;

worker_processes auto;

events {
    worker_connections 1024;
}

http {

    include mine.types

    server {

        listen 80;
        server_name 158.160.168.244;

        root /pididi;

        index index.php index.html;

        location / {
            try_files $uri $uri/ =404;
        }
        location ~\.php$ {
            include fastcgi.conf;
            fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        }

        location = /photo.png {
            add_header my_header "Hello World";
        }
    }
}