events {}

http {

    include mine.types
    server {
        listen 80;
        server_name 158.160.168.244;

        root /pididi;

        location /inspect {

            return 200 "Name : $arg_name";
        }
    }
}